#include <stdio.h>
using namespace std;
int main()
{
	cout<<11+12<<endl;
}DSAD WIOHQDHASOIHN .EBLWGLI USADASD OPWQEU3[4U4[09'SAHNF;JSKDHGPOIEAFADSFDSPGJFDSFHGJFNMDLVKNXC,MB,XZVBOWIHGTR RLGJDSKL EhN 